server:
  port: 7002


eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
    #集群指向其它eureka,当需要往注册中心集群注册服务时的写法：defaultZone:http://server1:8080/eureka,http://server2:8081/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
    #单机就是自己
      #defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000

spring:
  application:
    name: EurekaServer  #集群模式下，这个名字应该相同





